spring:
  application:
    name: spring-cloud-demo-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8765

feign:
  hystrix:
    enabled: true
#zuul:
#  ribbonIsolationStrategy: THREAD #设置Hystrix隔离策略为线程池
#  threadPool:
#    useSeparateThreadPools: true #每个路由使用独立的线程池
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled=false: false
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/